version: 0.2

phases:
  install:
    commands:
      - export PATH=$PATH:$(pwd)/vendor/tools/codebuild
      - export PATH=$PATH:$(pwd)/bin
      - docker-login
  pre_build:
    commands:
      - |
        #
        # Build test.
        #
        set -eu;
        build-test;
  build:
    commands:
      - |
        #
        # Push to ECR.
        #
        set -eu;
        if trigger is release ?; then
          push-to-ecr;
        fi;
  post_build:
    commands:
      - |
        #
        # Notify the result.
        #
        set -eu;
        notify-release-image rails-docker-image;
        notify-build-result rails-docker-image;
