version: 0.2

phases:
  install:
    commands:
      - export PATH=$PATH:$(pwd)/vendor/tools/codebuild
      - docker-login
  build:
    commands:
      - |
        #
        # Push to ECR.
        #
        set -eu;
        if trigger is release ?; then
          docker build -t codebuild:mzk .;
          docker tag codebuild:mzk 085041388644.dkr.ecr.ap-northeast-1.amazonaws.com/rails-docker-image:latest;
          docker tag codebuild:mzk 085041388644.dkr.ecr.ap-northeast-1.amazonaws.com/rails-docker-image:${CODEBUILD_WEBHOOK_TRIGGER#tag/};
        fi;
  post_build:
    commands:
      - |
        notify-release-image rails-docker-image;
