version: 0.2

phases:
  install:
    commands:
      - kill $(cat /var/run/docker.pid)
      - while kill -0 $(cat /var/run/docker.pid) ; do sleep 1 ; done
      - "echo '{ \"experimental\": true }' > /etc/docker/daemon.json"
      - /usr/local/bin/dockerd-entrypoint.sh
      - export PATH=$PATH:$(pwd)/vendor/tools/codebuild
      - export PATH=$PATH:$(pwd)/bin
      - export DOCKER_BUILDKIT=1
      - docker-login
  pre_build:
    commands:
      - |
        #
        # Build test.
        #
        set -eu;
        build-test;
  build:
    commands:
      - |
        #
        # Push to ECR.
        #
        set -eu;
        if trigger is release ?; then
          push-to-ecr ./Dockerfile.bullseye rails-docker-image bullseye;
          push-to-ecr ./Dockerfile.bullseye-slim rails-docker-image bullseye-slim;
          push-to-ecr ./Dockerfile.buster rails-docker-image buster;
          push-to-ecr ./Dockerfile.buster-slim rails-docker-image buster-slim;

          push-to-docker-hub ./Dockerfile.bullseye rails-docker-image bullseye;
          push-to-docker-hub ./Dockerfile.bullseye-slim rails-docker-image bullseye-slim;
          push-to-docker-hub ./Dockerfile.buster rails-docker-image buster;
          push-to-docker-hub ./Dockerfile.buster-slim rails-docker-image buster-slim;
        fi;
  post_build:
    commands:
      - |
        #
        # Notify the result.
        #
        set -eu;
        notify-release-image rails-docker-image;
        notify-build-result rails-docker-image;
